<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVgZdivo\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVgZdivo/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVgZdivo.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVgZdivo\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerVgZdivo\App_KernelProdContainer([
    'container.build_hash' => 'VgZdivo',
    'container.build_id' => 'f5dda78e',
    'container.build_time' => 1615197231,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVgZdivo');
