<?php

namespace ContainerVgZdivo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWeatherFormService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\form\WeatherForm' shared autowired service.
     *
     * @return \App\form\WeatherForm
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\form\\WeatherForm'] = new \App\form\WeatherForm();
    }
}
