index:
    path: /
    controller: App\Controller\CountryController::new


apicall:
    path: /data
    controller: App\Controller\GuzzleController::new

#test:
#    path: /test
#    controller:  App\Controller\testApiCall::newAction

