index:
    path: /
    controller: App\Controller\ApiCallController::post


apicall:
    path: /data
    controller: App\Controller\ApiCallController::post

#testApplication:
#  path: /data
#  controller: App\Controller\SubmittedData::test
