<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHQItTYs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHQItTYs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHQItTYs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHQItTYs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHQItTYs\App_KernelDevDebugContainer([
    'container.build_hash' => 'HQItTYs',
    'container.build_id' => 'f2f98e28',
    'container.build_time' => 1619012541,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHQItTYs');
