<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKdWmm2w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKdWmm2w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKdWmm2w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKdWmm2w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKdWmm2w\App_KernelDevDebugContainer([
    'container.build_hash' => 'KdWmm2w',
    'container.build_id' => '1b543c7c',
    'container.build_time' => 1620281347,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKdWmm2w');
