<?php

namespace ContainerZp9Nics;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWeatherFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\form\WeatherForm' shared autowired service.
     *
     * @return \App\form\WeatherForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/form/WeatherForm.php';

        return $container->privates['App\\form\\WeatherForm'] = new \App\form\WeatherForm();
    }
}
